### ISSUE TITLE
Required packages for building the f software aren't getting installed.

### ISSUE THREAD

**Issue by astroarshn2000** [uasal/fprime_demo#1]
# What was executed?
As I understand, you're supposed to clone 'fprime' repo from git to the local RPI. Did that. All the package and software are integrated inside this fprime directory.
Then you go to the mk directory and run the following:
 #### ./mk/os-pkg/ubuntu-packages.sh
#### sudo pip install -r  mk/python/pip_required_gui.txt

# Issues with the above.
#### ./mk/os-pkg/ubuntu-packages.sh
When I simply run the above line it gives me the error - 
_**E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?**_
Likely a sudo error. When I correct it and run sudo ./mk/os-pkg/ubuntu-packages.sh, I get the following - 
_**Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libwebkitgtk-3.0-cil' for regex 'gtk+-3.0'
Note, selecting 'libjavascriptcoregtk-3.0-bin' for regex 'gtk+-3.0'
Note, selecting 'libwebkitgtk-3.0-dev' for regex 'gtk+-3.0'
Note, selecting 'gir1.2-gtk-3.0' for regex 'gtk+-3.0'
Note, selecting 'libgtk-3-0-dbgsym' for regex 'gtk+-3.0'
Note, selecting 'libspice-client-gtk-3.0-dev' for regex 'gtk+-3.0'
Note, selecting 'libjavascriptcoregtk-3.0-dev' for regex 'gtk+-3.0'
Note, selecting 'libwebkit2gtk-3.0-25-dbg' for regex 'gtk+-3.0'
Note, selecting 'libgtk-3-0' for regex 'gtk+-3.0'
Note, selecting 'libwebkitgtk-3.0-0-dbg' for regex 'gtk+-3.0'
Note, selecting 'libwebkitgtk-3.0-common' for regex 'gtk+-3.0'
Note, selecting 'libwebkitgtk-3.0-0' for regex 'gtk+-3.0'
Note, selecting 'gir1.2-spice-client-gtk-3.0' for regex 'gtk+-3.0'
Note, selecting 'libwebkit2gtk-3.0-25' for regex 'gtk+-3.0'
Note, selecting 'libjavascriptcoregtk-3.0-0' for regex 'gtk+-3.0'
Note, selecting 'libspice-client-gtk-3.0-1' for regex 'gtk+-3.0'
Note, selecting 'libspice-client-gtk-3.0-5' for regex 'gtk+-3.0'
Note, selecting 'gir1.2-javascriptcoregtk-3.0' for regex 'gtk+-3.0'
Package libc6-i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'libc6-i386' has no installation candidate**_

#### sudo pip install -r  mk/python/pip_required_build.txt
When I simply run the above line it gives me the error - 
****Collecting Cheetah (from -r mk/python/pip_required_build.txt (line 1))
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)****

#### sudo pip install -r  mk/python/pip_required_gui.txt
When I simply run the above line it gives me the error -
_**Could not open requirements file: [Errno 2] No such file or directory: 'mk/python/pip_required_gui.txt'**_

**Comment by douglase** [comment]
did you install the debian developer tools on the raspberry pi before starting?
e.g. `sudo apt-get install build-essential`

https://raspberrypi.stackexchange.com/a/38241/106913

**Comment by douglase** [comment]
you are getting libc missing errors, essentials will install that, see https://packages.ubuntu.com/xenial/build-essential

**Comment by astroarshn2000** [comment]
Tried the command sudo apt-get install build-essential
Here's what I get-
**_Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded._**
Looks like debian developer tools are already upto the mark.
